CREATE DATABASE CulinaryBookDB;
GO
USE CulinaryBookDB;
GO
CREATE TABLE Authors (AuthorID INT IDENTITY PRIMARY KEY,AuthorName NVARCHAR(100) NOT NULL,Login NVARCHAR(50) NOT NULL UNIQUE,[Password] NVARCHAR(50) NOT NULL,BirthDay DATE NULL,Stage FLOAT NULL,Mail NVARCHAR(100) NULL,Number NVARCHAR(30) NULL);
CREATE TABLE Categories (CategoryID INT IDENTITY PRIMARY KEY,CategoryName NVARCHAR(100) NOT NULL);
CREATE TABLE Recipes (RecipeID INT IDENTITY PRIMARY KEY,RecipeName NVARCHAR(200) NOT NULL,[Description] NVARCHAR(MAX) NULL,CategoryID INT NOT NULL,AuthorID INT NOT NULL,CookingTime INT NULL,[Image] NVARCHAR(50) NULL,FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID),FOREIGN KEY (AuthorID) REFERENCES Authors(AuthorID));
CREATE TABLE RecipeImages (ImageID INT IDENTITY PRIMARY KEY,RecipeID INT NOT NULL,ImagePath NVARCHAR(255) NOT NULL,FOREIGN KEY (RecipeID) REFERENCES Recipes(RecipeID));
CREATE TABLE CookingSteps (StepID INT IDENTITY PRIMARY KEY,RecipeID INT NOT NULL,StepNumber INT NOT NULL,StepDescription NVARCHAR(MAX) NOT NULL,FOREIGN KEY (RecipeID) REFERENCES Recipes(RecipeID));
CREATE TABLE LikeRecipes (id INT IDENTITY PRIMARY KEY,idAuthor INT NOT NULL,idRecipes INT NOT NULL,FOREIGN KEY (idAuthor) REFERENCES Authors(AuthorID),FOREIGN KEY (idRecipes) REFERENCES Recipes(RecipeID));
CREATE TABLE Ingredients (IngredientID INT IDENTITY PRIMARY KEY,IngredientName NVARCHAR(100) NOT NULL);
CREATE TABLE RecipeIngredients (RecipeIngredientID INT IDENTITY PRIMARY KEY,RecipeID INT NOT NULL,IngredientID INT NOT NULL,Quantity NVARCHAR(50) NULL,FOREIGN KEY (RecipeID) REFERENCES Recipes(RecipeID),FOREIGN KEY (IngredientID) REFERENCES Ingredients(IngredientID));
